In [ ]:
import numpy as np
import pandas as pd
import socket
from sklearn.metrics import pairwise_distances
from sklearn.datasets import fetch_openml
from sklearn.datasets import load_files
from sklearn.feature_extraction.text import TfidfVectorizer


In [ ]:
newsgroups_train = load_files('20news-bydate/20news-bydate-train', encoding='ISO-8859-1')
newsgroups_test = load_files('20news-bydate/20news-bydate-test', encoding='ISO-8859-1')

X_train, y_train = newsgroups_train.data, newsgroups_train.target
X_test, y_test = newsgroups_test.data, newsgroups_test.target

print('Training Dataset Size: ', len(X_train))
print('Testing Dataset Size: ', len(X_test))
print('Number of Classes: ', len(newsgroups_train.target_names))

Training Dataset Size:  11314
Testing Dataset Size:  7532
Number of Classes:  20


In [ ]:

vectorizer = TfidfVectorizer(max_features=10000, stop_words='english')
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print(f"Shape of training data matrix: {X_train_tfidf.shape}")
print(f"Shape of testing data matrix: {X_test_tfidf.shape}")

Shape of training data matrix: (11314, 10000)
Shape of testing data matrix: (7532, 10000)


In [ ]:


euclidean_dist_library = pairwise_distances(X_train_tfidf, metric='euclidean')
print(f"Pairwise Euclidean Distance (Library):\n{euclidean_dist_library}")


Pairwise Euclidean Distance (Library):
[[0.         1.4070392  1.40986424 ... 1.40024178 1.40427376 1.40965994]
 [1.4070392  0.         1.39454536 ... 1.40739661 1.40466696 1.39033527]
 [1.40986424 1.39454536 0.         ... 1.3929457  1.40160715 1.40360347]
 ...
 [1.40024178 1.40739661 1.3929457  ... 0.         1.40768531 1.4127773 ]
 [1.40427376 1.40466696 1.40160715 ... 1.40768531 0.         1.41167435]
 [1.40965994 1.39033527 1.40360347 ... 1.4127773  1.41167435 0.        ]]


In [9]:
import numpy as np

def euclidean_distance_matrix(X):
    """
    Compute the pairwise Euclidean distance matrix using the efficient matrix formula.
    """
    # Compute the squared magnitudes of all vectors
    squared_norms = np.sum(X ** 2, axis=1, keepdims=True)  # Shape: (n_samples, 1)

    # Compute the distance matrix using the formula
    distance_matrix = np.sqrt(
        squared_norms + squared_norms.T - 2 * np.dot(X, X.T)
    )

    # Ensure no negative values due to floating-point errors
    distance_matrix = np.maximum(distance_matrix, 0)

    return distance_matrix

# Convert sparse matrix to dense
X_train_dense = X_train_tfidf.toarray()

# Calculate the Euclidean distance matrix
euclidean_dist_matrix = euclidean_distance_matrix(X_train_dense)

print(f"Pairwise Euclidean Distance Matrix:\n{euclidean_dist_matrix}")


Pairwise Euclidean Distance Matrix:
[[0.00000000e+00 1.40703920e+00 1.40986424e+00 ... 1.40024178e+00
  1.40427376e+00 1.40965994e+00]
 [1.40703920e+00 1.49011612e-08 1.39454536e+00 ... 1.40739661e+00
  1.40466696e+00 1.39033527e+00]
 [1.40986424e+00 1.39454536e+00            nan ... 1.39294570e+00
  1.40160715e+00 1.40360347e+00]
 ...
 [1.40024178e+00 1.40739661e+00 1.39294570e+00 ... 0.00000000e+00
  1.40768531e+00 1.41277730e+00]
 [1.40427376e+00 1.40466696e+00 1.40160715e+00 ... 1.40768531e+00
  0.00000000e+00 1.41167435e+00]
 [1.40965994e+00 1.39033527e+00 1.40360347e+00 ... 1.41277730e+00
  1.41167435e+00 1.49011612e-08]]


/var/folders/mg/w4cw2nc563q822jj2x4x_qqh0000gn/T/ipykernel_7907/3054068930.py:11: RuntimeWarning: invalid value encountered in sqrt
  distance_matrix = np.sqrt(


## MNIST Dataset - KNN

In [ ]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
import numpy as np

# Load MNIST dataset
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
X, y = mnist.data, mnist.target.astype(int)  # `X` is the feature matrix, `y` are labels

# Normalize pixel values to the range [0, 1]
X /= 255.0

# Split the data into train, validation, and test sets (80/10/10)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Print dataset shapes
print(f"Training data shape: {X_train.shape}")  # (56000, 784)
print(f"Validation data shape: {X_val.shape}")  # (7000, 784)
print(f"Testing data shape: {X_test.shape}")    # (7000, 784)


ModuleNotFoundError: No module named 'kagglehub'